workflows:
  flutter-release-workflow:   # rename this to match Codemagic
    name: Build Android Release APK
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.brick_r"
      android_signing:
        - keystore_credentials

    scripts:
      - name: 🔹 Clean project
        script: |
          flutter clean
          flutter pub get

      - name: 🔹 Analyze project
        script: |
          flutter analyze || true

      - name: 🔹 Build release APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - your-kr7013650812@gmail.com
          
          
