workflows:
  flutter-release-workflow:
    name: Build Android Release APK
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.brick_r"
    scripts:
      - name: 🔹 Clean and get packages
        script: |
          flutter clean
          flutter pub get

      - name: 🔹 Build release APK
        script: |
          flutter build apk --release --build-name=1.0.0 --build-number=1

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - your-kr7013650812@gmail.com
          
  
      
          
          
